[package]
name = "naive-html-parser"
version = "0.1.0"
authors = ["Henry <lkhh@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
